[build]
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ffmpeg-static"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
